# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/Cellar/cmake/2.8.11.2/bin/cmake

# The command to remove a file.
RM = /usr/local/Cellar/cmake/2.8.11.2/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The program to use to edit the cache.
CMAKE_EDIT_COMMAND = /usr/local/Cellar/cmake/2.8.11.2/bin/ccmake

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/bisegni/sorgenti/chaos_bundle_dev/example/ExampleControlUnit

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/bisegni/sorgenti/chaos_bundle_dev/example/ExampleControlUnit

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/Cellar/cmake/2.8.11.2/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/local/Cellar/cmake/2.8.11.2/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/local/Cellar/cmake/2.8.11.2/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/local/Cellar/cmake/2.8.11.2/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: install/local
.PHONY : install/local/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/Cellar/cmake/2.8.11.2/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/bisegni/sorgenti/chaos_bundle_dev/example/ExampleControlUnit/CMakeFiles /Users/bisegni/sorgenti/chaos_bundle_dev/example/ExampleControlUnit/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/bisegni/sorgenti/chaos_bundle_dev/example/ExampleControlUnit/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named ControlUnitTest

# Build rule for target.
ControlUnitTest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ControlUnitTest
.PHONY : ControlUnitTest

# fast build rule for target.
ControlUnitTest/fast:
	$(MAKE) -f CMakeFiles/ControlUnitTest.dir/build.make CMakeFiles/ControlUnitTest.dir/build
.PHONY : ControlUnitTest/fast

ControlUnitExample.o: ControlUnitExample.cpp.o
.PHONY : ControlUnitExample.o

# target to build an object file
ControlUnitExample.cpp.o:
	$(MAKE) -f CMakeFiles/ControlUnitTest.dir/build.make CMakeFiles/ControlUnitTest.dir/ControlUnitExample.cpp.o
.PHONY : ControlUnitExample.cpp.o

ControlUnitExample.i: ControlUnitExample.cpp.i
.PHONY : ControlUnitExample.i

# target to preprocess a source file
ControlUnitExample.cpp.i:
	$(MAKE) -f CMakeFiles/ControlUnitTest.dir/build.make CMakeFiles/ControlUnitTest.dir/ControlUnitExample.cpp.i
.PHONY : ControlUnitExample.cpp.i

ControlUnitExample.s: ControlUnitExample.cpp.s
.PHONY : ControlUnitExample.s

# target to generate assembly for a file
ControlUnitExample.cpp.s:
	$(MAKE) -f CMakeFiles/ControlUnitTest.dir/build.make CMakeFiles/ControlUnitTest.dir/ControlUnitExample.cpp.s
.PHONY : ControlUnitExample.cpp.s

DummyDriver.o: DummyDriver.cpp.o
.PHONY : DummyDriver.o

# target to build an object file
DummyDriver.cpp.o:
	$(MAKE) -f CMakeFiles/ControlUnitTest.dir/build.make CMakeFiles/ControlUnitTest.dir/DummyDriver.cpp.o
.PHONY : DummyDriver.cpp.o

DummyDriver.i: DummyDriver.cpp.i
.PHONY : DummyDriver.i

# target to preprocess a source file
DummyDriver.cpp.i:
	$(MAKE) -f CMakeFiles/ControlUnitTest.dir/build.make CMakeFiles/ControlUnitTest.dir/DummyDriver.cpp.i
.PHONY : DummyDriver.cpp.i

DummyDriver.s: DummyDriver.cpp.s
.PHONY : DummyDriver.s

# target to generate assembly for a file
DummyDriver.cpp.s:
	$(MAKE) -f CMakeFiles/ControlUnitTest.dir/build.make CMakeFiles/ControlUnitTest.dir/DummyDriver.cpp.s
.PHONY : DummyDriver.cpp.s

RTWorkerCU.o: RTWorkerCU.cpp.o
.PHONY : RTWorkerCU.o

# target to build an object file
RTWorkerCU.cpp.o:
	$(MAKE) -f CMakeFiles/ControlUnitTest.dir/build.make CMakeFiles/ControlUnitTest.dir/RTWorkerCU.cpp.o
.PHONY : RTWorkerCU.cpp.o

RTWorkerCU.i: RTWorkerCU.cpp.i
.PHONY : RTWorkerCU.i

# target to preprocess a source file
RTWorkerCU.cpp.i:
	$(MAKE) -f CMakeFiles/ControlUnitTest.dir/build.make CMakeFiles/ControlUnitTest.dir/RTWorkerCU.cpp.i
.PHONY : RTWorkerCU.cpp.i

RTWorkerCU.s: RTWorkerCU.cpp.s
.PHONY : RTWorkerCU.s

# target to generate assembly for a file
RTWorkerCU.cpp.s:
	$(MAKE) -f CMakeFiles/ControlUnitTest.dir/build.make CMakeFiles/ControlUnitTest.dir/RTWorkerCU.cpp.s
.PHONY : RTWorkerCU.cpp.s

SCWorkerCU.o: SCWorkerCU.cpp.o
.PHONY : SCWorkerCU.o

# target to build an object file
SCWorkerCU.cpp.o:
	$(MAKE) -f CMakeFiles/ControlUnitTest.dir/build.make CMakeFiles/ControlUnitTest.dir/SCWorkerCU.cpp.o
.PHONY : SCWorkerCU.cpp.o

SCWorkerCU.i: SCWorkerCU.cpp.i
.PHONY : SCWorkerCU.i

# target to preprocess a source file
SCWorkerCU.cpp.i:
	$(MAKE) -f CMakeFiles/ControlUnitTest.dir/build.make CMakeFiles/ControlUnitTest.dir/SCWorkerCU.cpp.i
.PHONY : SCWorkerCU.cpp.i

SCWorkerCU.s: SCWorkerCU.cpp.s
.PHONY : SCWorkerCU.s

# target to generate assembly for a file
SCWorkerCU.cpp.s:
	$(MAKE) -f CMakeFiles/ControlUnitTest.dir/build.make CMakeFiles/ControlUnitTest.dir/SCWorkerCU.cpp.s
.PHONY : SCWorkerCU.cpp.s

SinWaveCommand.o: SinWaveCommand.cpp.o
.PHONY : SinWaveCommand.o

# target to build an object file
SinWaveCommand.cpp.o:
	$(MAKE) -f CMakeFiles/ControlUnitTest.dir/build.make CMakeFiles/ControlUnitTest.dir/SinWaveCommand.cpp.o
.PHONY : SinWaveCommand.cpp.o

SinWaveCommand.i: SinWaveCommand.cpp.i
.PHONY : SinWaveCommand.i

# target to preprocess a source file
SinWaveCommand.cpp.i:
	$(MAKE) -f CMakeFiles/ControlUnitTest.dir/build.make CMakeFiles/ControlUnitTest.dir/SinWaveCommand.cpp.i
.PHONY : SinWaveCommand.cpp.i

SinWaveCommand.s: SinWaveCommand.cpp.s
.PHONY : SinWaveCommand.s

# target to generate assembly for a file
SinWaveCommand.cpp.s:
	$(MAKE) -f CMakeFiles/ControlUnitTest.dir/build.make CMakeFiles/ControlUnitTest.dir/SinWaveCommand.cpp.s
.PHONY : SinWaveCommand.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... ControlUnitTest"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... ControlUnitExample.o"
	@echo "... ControlUnitExample.i"
	@echo "... ControlUnitExample.s"
	@echo "... DummyDriver.o"
	@echo "... DummyDriver.i"
	@echo "... DummyDriver.s"
	@echo "... RTWorkerCU.o"
	@echo "... RTWorkerCU.i"
	@echo "... RTWorkerCU.s"
	@echo "... SCWorkerCU.o"
	@echo "... SCWorkerCU.i"
	@echo "... SCWorkerCU.s"
	@echo "... SinWaveCommand.o"
	@echo "... SinWaveCommand.i"
	@echo "... SinWaveCommand.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

